version: '3'

services:
  listen:
    build:
      context: .
      dockerfile: Dockerfile
    image: listen-service:local
    container_name: listen
    depends_on:
      - storage
    ports:
      - "127.0.0.1:1234:1234"
    networks:
      - web-net

  storage:
    image: postgres
    container_name: storage
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    volumes:
      - ./data:/var/lib/storage/data
    networks:
      - web-net
    healthcheck:
      test: pg_isready -U postgres -d users
      interval: 10s
      timeout: 3s
      retries: 5

  migrate:
    image: migrate/migrate
    networks:
      - web-net
    volumes:
      - ./schema:/schema
    depends_on:
      storage:
        condition: service_healthy
    command: ["-path", "./schema", "-database", "postgres://postgres:admin123@storage:5432/users?sslmode=disable", "up"]

networks:
  web-net:
    driver: bridge